//! `CounterCubit` — Phase 2 version using `#[cubit]` macro.
//!
//! Compare with `examples/v0.1/counter-dioxus/src/cubits/counter.rs` to see
//! the boilerplate that `#[cubit]` eliminates:
//!
//! **Before (v0.1) — manual:**
//! ```rust,ignore
//! struct CounterCubit { state: CounterState }
//! impl Cubit for CounterCubit { ... 10 lines ... }
//! impl CounterCubit { pub fn new(...) -> Self { ... } }
//! ```
//!
//! **After (v0.2) — with macro:**
//! ```rust,ignore
//! #[cubit(state = CounterState)]
//! pub struct CounterCubit {}
//! ```
//!
//! The `impl Cubit`, `new()`, and `on_change()` are all generated automatically.

use gloc::cubit;
use gloc::Cubit;

// ---------------------------------------------------------------------------
// State — developer-defined (Mode A: bring-your-own)
// ---------------------------------------------------------------------------

/// A snapshot of the counter's data at a single point in time.
///
/// Defined explicitly by the developer so full control over the shape is
/// retained. The macro does not touch this type.
#[derive(Clone, PartialEq, Debug)]
pub struct CounterState {
    /// The current counter value.
    pub count: i32,

    /// Human-readable label derived from the count magnitude.
    pub label: String,
}

impl CounterState {
    /// Constructs a new `CounterState`, deriving the label automatically.
    pub fn new(count: i32) -> Self {
        Self {
            label: Self::label_for(count),
            count,
        }
    }

    fn label_for(count: i32) -> String {
        match count {
            i32::MIN..=-1 => "Negative".into(),
            0 => "Zero".into(),
            1..=9 => "Low".into(),
            10..=99 => "Medium".into(),
            _ => "High".into(),
        }
    }
}

// ---------------------------------------------------------------------------
// Cubit — one line, macro generates everything else
// ---------------------------------------------------------------------------

/// Counter cubit — all boilerplate is generated by `#[cubit(state = CounterState)]`.
///
/// The macro generates:
/// - `impl Cubit for CounterCubit` (state(), emit() with change-detection)
/// - `pub fn new(initial: CounterState) -> Self`
/// - `pub fn on_change(callback: impl Fn(&CounterState) + 'static)`
#[cubit(state = CounterState)]
pub struct CounterCubit {}

impl CounterCubit {
    /// Increases the count by 1.
    pub fn increment(&mut self) {
        let next = self.state().count + 1;
        self.emit(CounterState::new(next));
    }

    /// Decreases the count by 1.
    pub fn decrement(&mut self) {
        let next = self.state().count - 1;
        self.emit(CounterState::new(next));
    }

    /// Resets the count to 0. No-op if already at 0 (change-detection).
    pub fn reset(&mut self) {
        self.emit(CounterState::new(0));
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use gloc::Cubit;

    #[test]
    fn new_sets_initial_state() {
        let c = CounterCubit::new(CounterState::new(0));
        assert_eq!(c.state().count, 0);
        assert_eq!(c.state().label, "Zero");
    }

    #[test]
    fn increment_updates_count_and_label() {
        let mut c = CounterCubit::new(CounterState::new(0));
        c.increment();
        assert_eq!(c.state().count, 1);
        assert_eq!(c.state().label, "Low");
    }

    #[test]
    fn decrement_from_zero_gives_negative_label() {
        let mut c = CounterCubit::new(CounterState::new(0));
        c.decrement();
        assert_eq!(c.state().count, -1);
        assert_eq!(c.state().label, "Negative");
    }

    #[test]
    fn reset_returns_to_zero() {
        let mut c = CounterCubit::new(CounterState::new(50));
        c.reset();
        assert_eq!(c.state().count, 0);
    }

    #[test]
    fn reset_on_zero_is_noop() {
        let mut c = CounterCubit::new(CounterState::new(0));
        let before = c.state().clone();
        c.reset();
        assert_eq!(c.state(), &before);
    }

    #[test]
    fn on_change_fires_on_transition() {
        use std::cell::Cell;
        use std::rc::Rc;

        let mut c = CounterCubit::new(CounterState::new(0));
        let fired = Rc::new(Cell::new(false));
        let f = fired.clone();
        c.on_change(move |_| f.set(true));
        c.increment();
        assert!(fired.get());
    }

    #[test]
    fn on_change_does_not_fire_on_noop() {
        use std::cell::Cell;
        use std::rc::Rc;

        let mut c = CounterCubit::new(CounterState::new(0));
        let count = Rc::new(Cell::new(0_u32));
        let cnt = count.clone();
        c.on_change(move |_| cnt.set(cnt.get() + 1));
        c.reset(); // already at 0 — no-op
        assert_eq!(count.get(), 0);
    }

    #[test]
    fn satisfies_cubit_trait_object() {
        let c = CounterCubit::new(CounterState::new(0));
        fn accept(_: &dyn Cubit<State = CounterState>) {}
        accept(&c);
    }
}
