//! Shared code generation utilities used by both Mode A and Mode B.
//!
//! Each function in this module produces a [`TokenStream`] fragment that is
//! assembled by the mode-specific modules into the final macro output. Keeping
//! generation here in one place means the two modes stay in sync automatically.

use proc_macro2::TokenStream;
use quote::quote;
use syn::{Field, Ident, Path, Type};

/// Generates the `impl ::gloc::Reactor for <struct_name>` block.
///
/// Wires up:
/// - `type State = <state_type>`
/// - `fn state()` — returns a reference to `self.__gloc_state`
/// - `fn emit()` — change-detection, optional tracing, then
///   `__gloc_stream.emit_transition(old, new)` if observers enabled
///
/// # Parameters
///
/// - `struct_name`   — the reactor struct's identifier
/// - `state_type`    — the `syn::Type` of the State
/// - `has_observers` — when `true`, emit pushes transitions into `__gloc_stream`
pub fn impl_reactor(struct_name: &Ident, state_type: &Type, has_observers: bool) -> TokenStream {
    let stream_call = if has_observers {
        quote! {
            self.__gloc_stream.emit_transition(&__gloc_old, &self.__gloc_state);
        }
    } else {
        quote! {}
    };

    let tracing_call = if cfg!(feature = "tracing") {
        quote! {
            ::tracing::debug!(
                reactor = ::std::stringify!(#struct_name),
                old     = ?__gloc_old,
                new     = ?next,
            );
        }
    } else {
        quote! {}
    };

    // Always capture old state — needed for stream, tracing, and global observer.
    let capture_old = quote! { let __gloc_old = self.__gloc_state.clone(); };

    // Global observer notification — fires after stream so listeners run first.
    let observer_call = quote! {
        if let ::std::option::Option::Some(__gloc_obs) = ::gloc::observer() {
            __gloc_obs.on_transition(
                ::std::any::type_name::<Self>(),
                &::std::format!("{:?}", __gloc_old),
                &::std::format!("{:?}", self.__gloc_state),
            );
        }
    };

    quote! {
        #[automatically_derived]
        impl ::gloc::Reactor for #struct_name {
            type State = #state_type;

            /// Returns a shared reference to the reactor's current state.
            ///
            /// Generated by `#[reactor]`. State is stored in `__gloc_state`.
            fn state(&self) -> &#state_type {
                &self.__gloc_state
            }

            /// Transitions to `next` if it differs from the current state.
            ///
            /// Generated by `#[reactor]`:
            /// 1. Change-detection guard — no-op if `next == current`
            /// 2. Optional tracing log (baked in at macro-expansion time)
            /// 3. State update
            /// 4. Stream notification — fires all registered listeners with (old, new)
            fn emit(&mut self, next: #state_type) {
                if next != self.__gloc_state {
                    #capture_old
                    #tracing_call
                    self.__gloc_state = next.clone();
                    #stream_call
                    #observer_call
                }
            }
        }
    }
}

/// Generates `pub fn new(/* extra fields */, initial: StateType) -> Self`.
///
/// Extra user-defined fields become leading parameters before `initial`.
///
/// # Parameters
///
/// - `struct_name`   — the reactor struct's identifier
/// - `state_type`    — the State type
/// - `has_observers` — whether to initialise `__gloc_stream`
/// - `extra_fields`  — non-state fields on the reactor struct
pub fn impl_new(
    struct_name: &Ident,
    state_type: &Type,
    has_observers: bool,
    extra_fields: &[Field],
) -> TokenStream {
    let stream_init = if has_observers {
        quote! {
            __gloc_stream: ::gloc::GlocStream::new(initial.clone()),
        }
    } else {
        quote! {}
    };

    let extra_params = extra_fields.iter().map(|f| {
        let name = f.ident.as_ref().expect("named field");
        let ty = &f.ty;
        quote! { #name: #ty }
    });

    let extra_inits = extra_fields.iter().map(|f| {
        let name = f.ident.as_ref().expect("named field");
        quote! { #name, }
    });

    quote! {
        impl #struct_name {
            /// Creates a new reactor with the given `initial` state.
            ///
            /// Generated by `#[reactor]`. Extra fields on the reactor struct appear
            /// as additional parameters before `initial`, in declaration order.
            ///
            /// To suppress this and write your own constructor, use `#[reactor(no_new)]`.
            pub fn new(#(#extra_params,)* initial: #state_type) -> Self {
                // Stream is initialised first so `initial.clone()` runs before
                // `initial` is moved into `__gloc_state`.
                Self {
                    #(#extra_inits)*
                    #stream_init
                    __gloc_state: initial,
                }
            }
        }
    }
}

/// Generates `pub fn fire(&mut self, event: EventType)`.
///
/// The generated method simply calls `self.on_event(neutron)`, which the user
/// writes in any impl block. `on_event` calls `emit()` internally, so
/// change-detection, stream notification, and global observer all fire as normal.
///
/// # Parameters
///
/// - `struct_name` — the reactor struct's identifier
/// - `neutron_type`  — the event enum type (from `events = MyEvent`)
pub fn impl_fire(struct_name: &Ident, neutron_type: &Type) -> TokenStream {
    quote! {
        impl #struct_name {
            /// Dispatches `event` to this reactor's `on_event` handler.
            ///
            /// Generated by `#[reactor(events = E)]`. Write
            /// `fn on_event(&mut self, event: E)` in any impl block to define
            /// how each event transitions the state.
            ///
            /// The event type must implement [`gloc::Event`] — any
            /// `Debug + Send + 'static` type satisfies this automatically via
            /// the blanket impl.
            ///
            /// Both direct method calls and `dispatch()` can be used on the
            /// same reactor — they are not mutually exclusive.
            pub fn fire(&mut self, neutron: #neutron_type)
            where
                #neutron_type: ::gloc::Neutron,
            {
                self.on_event(neutron);
            }
        }
    }
}

/// Generates `impl Deref<Target = StateType> for StructName`.
///
/// Lets callers reach state fields directly through the reactor reference —
/// `reactor.count` instead of `reactor.state().count`.
pub fn impl_deref(struct_name: &Ident, state_type: &Type) -> TokenStream {
    quote! {
        #[automatically_derived]
        impl ::std::ops::Deref for #struct_name {
            type Target = #state_type;
            fn deref(&self) -> &#state_type {
                &self.__gloc_state
            }
        }
    }
}

/// Converts a `syn::Path` into a `syn::Type` for use in codegen.
pub fn path_to_type(path: &Path) -> Type {
    Type::Path(syn::TypePath {
        qself: None,
        path: path.clone(),
    })
}
