//! Shared code generation utilities used by both Mode A and Mode B.
//!
//! Each function in this module produces a [`TokenStream`] fragment that is
//! assembled by the mode-specific modules into the final macro output. Keeping
//! generation here in one place means the two modes stay in sync automatically.

use proc_macro2::TokenStream;
use quote::quote;
use syn::{Field, Ident, Path, Type};

/// Generates the `impl ::gloc::Cubit for <struct_name>` block.
///
/// This is the mandatory output of every `#[cubit]` invocation. It wires up:
///
/// - `type State = <state_type>`
/// - `fn state()` — returns a reference to `self.__gloc_state`
/// - `fn emit()` — applies change-detection, optional tracing, and fires
///   any registered `on_change` listeners
///
/// # Parameters
///
/// - `struct_name`   — the cubit struct's identifier (e.g. `CounterCubit`)
/// - `state_type`    — the `syn::Type` of the State (e.g. `CounterState`)
/// - `has_observers` — when `true`, the generated `emit()` iterates listeners;
///   when `false` the listener loop is omitted (mirrors `no_observers` arg)
pub fn impl_cubit(struct_name: &Ident, state_type: &Type, has_observers: bool) -> TokenStream {
    let listener_call = if has_observers {
        quote! {
            for __listener in &self.__gloc_listeners {
                __listener(&self.__gloc_state);
            }
        }
    } else {
        quote! {}
    };

    quote! {
        #[automatically_derived]
        impl ::gloc::Cubit for #struct_name {
            type State = #state_type;

            /// Returns a shared reference to the cubit's current state.
            ///
            /// This method is generated by `#[cubit]`. The state is stored in
            /// the private `__gloc_state` field injected by the macro.
            fn state(&self) -> &#state_type {
                &self.__gloc_state
            }

            /// Transitions to `next` if it differs from the current state.
            ///
            /// This method is generated by `#[cubit]`. It:
            /// 1. Guards against redundant emissions via `PartialEq`.
            /// 2. Emits a `tracing::debug!` log (when the `tracing` feature is enabled).
            /// 3. Stores the new state.
            /// 4. Fires all registered `on_change` listeners in registration order.
            fn emit(&mut self, next: #state_type) {
                if next != self.__gloc_state {
                    #[cfg(feature = "tracing")]
                    ::tracing::debug!(
                        cubit = ::std::stringify!(#struct_name),
                        old   = ?self.__gloc_state,
                        new   = ?next,
                    );
                    self.__gloc_state = next;
                    #listener_call
                }
            }
        }
    }
}

/// Generates `pub fn new(/* extra fields */, initial: StateType) -> Self`.
///
/// The generated constructor is the standard entry point for creating a cubit.
/// Extra user-defined fields on the cubit struct (non-infrastructure fields)
/// become additional parameters that appear before `initial`, in declaration
/// order, so the developer can supply them at construction time.
///
/// # Parameters
///
/// - `struct_name`   — the cubit struct's identifier
/// - `state_type`    — the State type used as the last constructor parameter
/// - `has_observers` — whether to include the `__gloc_listeners` initialiser
/// - `extra_fields`  — the user-defined fields on the cubit (not the state fields);
///   each becomes a named parameter in the generated `new()` signature
pub fn impl_new(
    struct_name: &Ident,
    state_type: &Type,
    has_observers: bool,
    extra_fields: &[Field],
) -> TokenStream {
    let listeners_init = if has_observers {
        quote! { __gloc_listeners: ::std::vec::Vec::new(), }
    } else {
        quote! {}
    };

    // Build the extra parameter list: `field_name: FieldType, ...`
    let extra_params = extra_fields.iter().map(|f| {
        let name = f.ident.as_ref().expect("named field");
        let ty = &f.ty;
        quote! { #name: #ty }
    });

    // Build the initialiser expressions for those fields: `field_name,`
    let extra_inits = extra_fields.iter().map(|f| {
        let name = f.ident.as_ref().expect("named field");
        quote! { #name, }
    });

    quote! {
        impl #struct_name {
            /// Creates a new cubit with the given `initial` state.
            ///
            /// Generated by `#[cubit]`. Extra fields on the cubit struct appear
            /// as additional parameters before `initial`, in declaration order.
            ///
            /// To suppress this constructor and write your own, add `no_new`
            /// to the attribute: `#[cubit(no_new)]`.
            pub fn new(#(#extra_params,)* initial: #state_type) -> Self {
                Self {
                    #(#extra_inits)*
                    __gloc_state: initial,
                    #listeners_init
                }
            }
        }
    }
}

/// Generates `pub fn on_change(&mut self, callback: impl Fn(&StateType) + 'static)`.
///
/// The generated method registers a callback that is called every time
/// [`Cubit::emit`] transitions to a new state. Callbacks are called in the
/// order they were registered.
///
/// # Parameters
///
/// - `struct_name` — the cubit struct's identifier
/// - `state_type`  — the State type; used in the callback closure signature
pub fn impl_on_change(struct_name: &Ident, state_type: &Type) -> TokenStream {
    quote! {
        impl #struct_name {
            /// Registers `callback` to be called every time the cubit transitions to a new state.
            ///
            /// Generated by `#[cubit]`. Callbacks fire synchronously inside `emit()`,
            /// in the order they were registered, after the state has been updated.
            ///
            /// To suppress this method, add `no_observers` to the attribute:
            /// `#[cubit(no_observers)]`.
            pub fn on_change(&mut self, callback: impl Fn(&#state_type) + 'static) {
                self.__gloc_listeners.push(::std::boxed::Box::new(callback));
            }
        }
    }
}

/// Converts a `syn::Path` into a `syn::Type` for use in codegen.
///
/// Proc macros often receive state types as `Path` from attribute parsing but
/// the codegen functions expect a `Type`. This helper wraps the path cleanly.
pub fn path_to_type(path: &Path) -> Type {
    Type::Path(syn::TypePath {
        qself: None,
        path: path.clone(),
    })
}
