//! Mode B code generation — generate the State struct from `#[state]` fields.
//!
//! Activated when the developer annotates individual fields with `#[state]`
//! and omits the `state = SomeType` argument.
//!
//! ## What this module generates
//!
//! Given:
//! ```rust,ignore
//! #[cubit]
//! struct CounterCubit {
//!     #[state] count: i32,
//!     step: i32,           // non-state field — stays on the cubit
//! }
//! ```
//!
//! It produces:
//! ```rust,ignore
//! // Generated State struct (name = cubit name + "State")
//! #[derive(Clone, PartialEq, Debug)]
//! pub struct CounterCubitState {
//!     pub count: i32,
//! }
//!
//! // Cubit struct with non-state fields + injected infrastructure fields
//! struct CounterCubit {
//!     step: i32,
//!     __gloc_state: CounterCubitState,
//!     __gloc_listeners: Vec<Box<dyn Fn(&CounterCubitState)>>,
//! }
//!
//! impl ::gloc::Cubit for CounterCubit { ... }
//! impl CounterCubit { pub fn new(...) -> Self { ... } }
//! impl CounterCubit { pub fn on_change(...) { ... } }
//! ```

use proc_macro2::{Ident, Span, TokenStream};
use quote::quote;
use syn::{Field, Fields, ItemStruct, Type};

use crate::args::CubitArgs;
use crate::codegen::{impl_cubit, impl_new, impl_on_change};
use crate::errors::error;

/// Entry point for Mode B expansion.
///
/// # Parameters
///
/// - `item` — the parsed cubit struct from the user's source.
/// - `args` — the full parsed attribute args (for `no_new`, `no_observers`).
///
/// # Errors
///
/// Returns a `compile_error!` token stream if:
/// - The struct has no `#[state]` fields — the macro cannot infer the State type.
/// - The struct uses unnamed (tuple) fields.
pub fn expand(item: &ItemStruct, args: &CubitArgs) -> TokenStream {
    // Guard: tuple structs not supported.
    if matches!(item.fields, Fields::Unnamed(_)) {
        return error(
            &item.fields,
            "#[cubit] does not support tuple structs. Use named fields: `struct Foo { ... }`.",
        );
    }

    let named_fields = match &item.fields {
        Fields::Named(f) => &f.named,
        // Unit struct with no fields — checked for #[state] below.
        _ => {
            return error(
                item,
                "#[cubit] requires at least one `#[state]` field, or use `#[cubit(state = SomeType)]` \
                 to supply an existing State type.",
            )
        }
    };

    // Partition fields into state fields and regular cubit fields.
    let mut state_fields: Vec<&Field> = Vec::new();
    let mut cubit_fields: Vec<Field>  = Vec::new();

    for field in named_fields {
        let is_state = field.attrs.iter().any(|a| a.path().is_ident("state"));
        if is_state {
            state_fields.push(field);
        } else {
            cubit_fields.push(field.clone());
        }
    }

    // Guard: at least one #[state] field is required.
    if state_fields.is_empty() {
        return error(
            item,
            "#[cubit] requires at least one field annotated with `#[state]`. \
             Example: `#[state] count: i32`. \
             Alternatively, supply an existing state type: `#[cubit(state = MyState)]`.",
        );
    }

    let struct_name  = &item.ident;
    let vis          = &item.vis;
    let has_observers = !args.no_observers;

    // Build the generated State struct name: e.g. CounterCubit → CounterCubitState
    let state_name = Ident::new(&format!("{}State", struct_name), Span::call_site());

    // Strip #[state] attrs from the state fields in the generated struct,
    // and make them `pub` so callers can read them.
    let state_struct_fields = state_fields.iter().map(|f| {
        let mut f = (*f).clone();
        f.attrs.retain(|a| !a.path().is_ident("state"));
        // Force public visibility on generated state fields.
        f.vis = syn::Visibility::Public(syn::token::Pub::default());
        f
    });

    // --- Generated State struct ---
    let state_struct = quote! {
        /// State snapshot generated by `#[cubit]`.
        ///
        /// This struct is auto-generated from all fields annotated with `#[state]`
        /// on the parent cubit. Its name is the cubit's name suffixed with `State`.
        #[derive(Clone, PartialEq, Debug)]
        #vis struct #state_name {
            #(#state_struct_fields,)*
        }
    };

    // Build the state type as a syn::Type for codegen helpers.
    let state_type: Type = syn::parse_quote!(#state_name);

    // Infrastructure fields injected into the cubit struct.
    let state_field = quote! {
        __gloc_state: #state_name,
    };
    let listeners_field = if has_observers {
        quote! {
            __gloc_listeners: ::std::vec::Vec<::std::boxed::Box<dyn Fn(&#state_name)>>,
        }
    } else {
        quote! {}
    };

    // Filter cubit-level attrs (strip the #[cubit] attribute itself).
    let cubit_attrs = item.attrs.iter().filter(|a| !a.path().is_ident("cubit"));

    // --- Rewritten cubit struct ---
    let rewritten_struct = quote! {
        #(#cubit_attrs)*
        #vis struct #struct_name {
            #(#cubit_fields,)*
            #state_field
            #listeners_field
        }
    };

    let cubit_impl    = impl_cubit(struct_name, &state_type, has_observers);
    let new_impl      = if args.no_new { quote! {} } else { impl_new(struct_name, &state_type, has_observers, &cubit_fields) };
    let observer_impl = if has_observers { impl_on_change(struct_name, &state_type) } else { quote! {} };

    quote! {
        #state_struct
        #rewritten_struct
        #cubit_impl
        #new_impl
        #observer_impl
    }
}
