//! Mode B code generation — generate the State struct from `#[state]` fields.
//!
//! Activated when the developer annotates individual fields with `#[state]`
//! and omits the `state = SomeType` argument.
//!
//! ## What this module generates
//!
//! Given:
//! ```rust,ignore
//! #[reactor]
//! struct CounterReactor {
//!     #[state] count: i32,
//!     step: i32,           // non-state field — stays on the reactor
//! }
//! ```
//!
//! It produces:
//! ```rust,ignore
//! // Generated State struct (name = reactor name + "State")
//! #[derive(Clone, PartialEq, Debug)]
//! pub struct CounterReactorState {
//!     pub count: i32,
//! }
//!
//! // Reactor struct with non-state fields + injected infrastructure fields
//! struct CounterReactor {
//!     step: i32,
//!     __gloc_state: CounterReactorState,
//!     __gloc_stream: ::gloc::GlocStream<CounterReactorState>,
//! }
//!
//! impl ::gloc::Reactor for CounterReactor { ... }
//! impl CounterReactor { pub fn new(...) -> Self { ... } }
//! ```

use proc_macro2::{Ident, Span, TokenStream};
use quote::quote;
use syn::{Field, Fields, ItemStruct, Type};

use crate::args::CubitArgs;
use crate::codegen::{impl_deref, impl_fire, impl_new, impl_reactor, path_to_type};
use crate::errors::error;

/// Entry point for Mode B expansion.
///
/// # Parameters
///
/// - `item` — the parsed reactor struct from the user's source.
/// - `args` — the full parsed attribute args (for `no_new`, `no_observers`).
///
/// # Errors
///
/// Returns a `compile_error!` token stream if:
/// - The struct has no `#[state]` fields — the macro cannot infer the State type.
/// - The struct uses unnamed (tuple) fields.
pub fn expand(item: &ItemStruct, args: &CubitArgs) -> TokenStream {
    // Guard: tuple structs not supported.
    if matches!(item.fields, Fields::Unnamed(_)) {
        return error(
            &item.fields,
            "#[reactor] does not support tuple structs. Use named fields: `struct Foo { ... }`.",
        );
    }

    let named_fields = match &item.fields {
        Fields::Named(f) => &f.named,
        _ => return error(
            item,
            "#[reactor] requires at least one `#[state]` field, or use `#[reactor(state = SomeType)]` \
                 to supply an existing State type.",
        ),
    };

    // Partition fields into state fields and regular reactor fields.
    let mut state_fields: Vec<&Field> = Vec::new();
    let mut reactor_fields: Vec<Field> = Vec::new();

    for field in named_fields {
        let is_state = field.attrs.iter().any(|a| a.path().is_ident("state"));
        if is_state {
            state_fields.push(field);
        } else {
            reactor_fields.push(field.clone());
        }
    }

    // Guard: at least one #[state] field is required.
    if state_fields.is_empty() {
        return error(
            item,
            "#[reactor] requires at least one field annotated with `#[state]`. \
             Example: `#[state] count: i32`. \
             Alternatively, supply an existing state type: `#[reactor(state = MyState)]`.",
        );
    }

    let struct_name = &item.ident;
    let vis = &item.vis;

    // Build the generated State struct name: e.g. CounterReactor → CounterReactorState
    let state_name = Ident::new(&format!("{}State", struct_name), Span::call_site());

    // Strip #[state] attrs from the state fields in the generated struct,
    // and make them `pub` so callers can read them.
    let state_struct_fields = state_fields.iter().map(|f| {
        let mut f = (*f).clone();
        f.attrs.retain(|a| !a.path().is_ident("state"));
        // Force public visibility on generated state fields.
        f.vis = syn::Visibility::Public(syn::token::Pub::default());
        f
    });

    // --- Generated State struct ---
    let state_struct = quote! {
        /// State snapshot generated by `#[reactor]`.
        ///
        /// This struct is auto-generated from all fields annotated with `#[state]`
        /// on the parent reactor. Its name is the reactor's name suffixed with `State`.
        #[derive(Clone, PartialEq, Debug)]
        #vis struct #state_name {
            #(#state_struct_fields,)*
        }
    };

    // Build the state type as a syn::Type for codegen helpers.
    let state_type: Type = syn::parse_quote!(#state_name);

    // Infrastructure fields injected into the reactor struct.
    // `__gloc_state` holds the current state value.
    // `__gloc_stream` is always present — `GlocObserver` uses it via `emit()`.
    let state_field = quote! {
        __gloc_state: #state_name,
    };
    let stream_field = quote! {
        __gloc_stream: ::gloc::GlocStream<#state_name>,
    };

    // Filter reactor-level attrs (strip the #[reactor] attribute itself).
    let reactor_attrs = item.attrs.iter().filter(|a| !a.path().is_ident("reactor"));

    // --- Rewritten reactor struct ---
    let rewritten_struct = quote! {
        #(#reactor_attrs)*
        #vis struct #struct_name {
            #(#reactor_fields,)*
            #state_field
            #stream_field
        }
    };

    let reactor_impl = impl_reactor(struct_name, &state_type, true);
    let new_impl = if args.no_new {
        quote! {}
    } else {
        impl_new(struct_name, &state_type, true, &reactor_fields)
    };

    let deref_impl = impl_deref(struct_name, &state_type);
    let fire_impl = if let Some(event_path) = &args.neutrons {
        let neutron_type = path_to_type(event_path);
        impl_fire(struct_name, &neutron_type)
    } else {
        quote! {}
    };

    quote! {
        #state_struct
        #rewritten_struct
        #reactor_impl
        #deref_impl
        #new_impl
        #fire_impl
    }
}
