//! `CounterReactor` — Phase 2 version using `#[reactor]` macro.
//!
//! Compare with `examples/v0.1/counter-dioxus/src/cubits/counter.rs` to see
//! the boilerplate that `#[reactor]` eliminates:
//!
//! **Before (v0.1) — manual:**
//! ```rust,ignore
//! struct CounterReactor { state: CounterState }
//! impl Reactor for CounterReactor { ... 10 lines ... }
//! impl CounterReactor { pub fn new(...) -> Self { ... } }
//! ```
//!
//! **After (v0.2) — with macro:**
//! ```rust,ignore
//! #[reactor(state = CounterState)]
//! pub struct CounterReactor {}
//! ```
//!
//! The `impl Reactor` and `new()` are all generated automatically.
use gloc::reactor;
use gloc::Reactor;
// ---------------------------------------------------------------------------
// State — developer-defined (Mode A: bring-your-own)
// ---------------------------------------------------------------------------
/// A snapshot of the counter's data at a single point in time.
///
/// Defined explicitly by the developer so full control over the shape is
/// retained. The macro does not touch this type.
#[derive(Clone, PartialEq, Debug)]
pub struct CounterState {
    /// The current counter value.
    pub count: i32,
    /// Human-readable label derived from the count magnitude.
    pub label: String,
}
impl CounterState {
    /// Constructs a new `CounterState`, deriving the label automatically.
    pub fn new(count: i32) -> Self {
        Self {
            label: Self::label_for(count),
            count,
        }
    }
    fn label_for(count: i32) -> String {
        match count {
            i32::MIN..=-1 => "Negative".into(),
            0 => "Zero".into(),
            1..=9 => "Low".into(),
            10..=99 => "Medium".into(),
            _ => "High".into(),
        }
    }
}
// ---------------------------------------------------------------------------
// Cubit — one line, macro generates everything else
// ---------------------------------------------------------------------------
/// Counter reactor — all boilerplate is generated by `#[reactor(state = CounterState)]`.
///
/// The macro generates:
/// - `impl Reactor for CounterReactor` (state(), emit() with change-detection)
/// - `pub fn new(initial: CounterState) -> Self`
/// - `subscribe()` and `attach_listener()` for observing transitions
#[reactor(state = CounterState)]
pub struct CounterReactor {}
impl CounterReactor {
    /// Increases the count by 1.
    pub fn increment(&mut self) {
        let next = self.state().count + 1;
        self.emit(CounterState::new(next));
    }
    /// Decreases the count by 1.
    pub fn decrement(&mut self) {
        let next = self.state().count - 1;
        self.emit(CounterState::new(next));
    }
    /// Resets the count to 0. No-op if already at 0 (change-detection).
    pub fn reset(&mut self) {
        self.emit(CounterState::new(0));
    }
}
// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use gloc_test::{reactor_test, ReactorTester};

    use super::*;

    fn counter(n: i32) -> CounterReactor {
        CounterReactor::new(CounterState::new(n))
    }

    // ---- happy path ----

    #[test]
    fn increment_increases_count() {
        reactor_test! {
            build: counter(0),
            acts: [|r| r.increment()],
            expect_states: [CounterState::new(1)],
        }
    }

    #[test]
    fn decrement_decreases_count() {
        reactor_test! {
            build: counter(5),
            acts: [|r| r.decrement()],
            expect_states: [CounterState::new(4)],
        }
    }

    #[test]
    fn reset_returns_to_zero() {
        reactor_test! {
            build: counter(10),
            acts: [|r| r.reset()],
            expect_states: [CounterState::new(0)],
        }
    }

    #[test]
    fn increment_sequence_captures_each_step() {
        reactor_test! {
            build: counter(0),
            acts: [
                |r| r.increment(),
                |r| r.increment(),
                |r| r.increment(),
            ],
            expect_states: [
                CounterState::new(1),
                CounterState::new(2),
                CounterState::new(3),
            ],
        }
    }

    #[test]
    fn mixed_sequence_is_captured_in_order() {
        reactor_test! {
            build: counter(0),
            acts: [
                |r| r.increment(),
                |r| r.increment(),
                |r| r.decrement(),
                |r| r.reset(),
            ],
            expect_states: [
                CounterState::new(1),
                CounterState::new(2),
                CounterState::new(1),
                CounterState::new(0),
            ],
        }
    }

    // ---- edge cases ----

    #[test]
    fn reset_from_zero_emits_nothing() {
        // Change-detection: emitting an equal state is silently swallowed.
        reactor_test! {
            build: counter(0),
            acts: [|r| r.reset()],
            expect_no_emissions: true,
        }
    }

    #[test]
    fn count_goes_negative() {
        reactor_test! {
            build: counter(0),
            acts: [|r| r.decrement()],
            expect_states: [CounterState::new(-1)],
        }
    }

    // ---- boundary: label transitions at count thresholds ----

    #[test]
    fn label_is_zero_at_zero() {
        let tester = ReactorTester::new(counter(0));
        assert_eq!(tester.state().label, "Zero");
    }

    #[test]
    fn label_transitions_low_to_medium_at_ten() {
        let tester = ReactorTester::new(counter(9));
        tester.act(|r| r.increment());
        assert_eq!(tester.state().label, "Medium");
    }

    #[test]
    fn label_transitions_medium_to_high_at_hundred() {
        let tester = ReactorTester::new(counter(99));
        tester.act(|r| r.increment());
        assert_eq!(tester.state().label, "High");
    }

    #[test]
    fn label_is_negative_below_zero() {
        let tester = ReactorTester::new(counter(0));
        tester.act(|r| r.decrement());
        assert_eq!(tester.state().label, "Negative");
    }
}
