//! `CounterReactor` — Phase 2 version using `#[reactor]` macro.
//!
//! Compare with `examples/v0.1/counter-dioxus/src/cubits/counter.rs` to see
//! the boilerplate that `#[reactor]` eliminates:
//!
//! **Before (v0.1) — manual:**
//! ```rust,ignore
//! struct CounterReactor { state: CounterState }
//! impl Reactor for CounterReactor { ... 10 lines ... }
//! impl CounterReactor { pub fn new(...) -> Self { ... } }
//! ```
//!
//! **After (v0.2) — with macro:**
//! ```rust,ignore
//! #[reactor(state = CounterState)]
//! pub struct CounterReactor {}
//! ```
//!
//! The `impl Reactor` and `new()` are all generated automatically.
use gloc::reactor;
use gloc::Reactor;
// ---------------------------------------------------------------------------
// State — developer-defined (Mode A: bring-your-own)
// ---------------------------------------------------------------------------
/// A snapshot of the counter's data at a single point in time.
///
/// Defined explicitly by the developer so full control over the shape is
/// retained. The macro does not touch this type.
#[derive(Clone, PartialEq, Debug)]
pub struct CounterState {
    /// The current counter value.
    pub count: i32,
    /// Human-readable label derived from the count magnitude.
    pub label: String,
}
impl CounterState {
    /// Constructs a new `CounterState`, deriving the label automatically.
    pub fn new(count: i32) -> Self {
        Self {
            label: Self::label_for(count),
            count,
        }
    }
    fn label_for(count: i32) -> String {
        match count {
            i32::MIN..=-1 => "Negative".into(),
            0 => "Zero".into(),
            1..=9 => "Low".into(),
            10..=99 => "Medium".into(),
            _ => "High".into(),
        }
    }
}
// ---------------------------------------------------------------------------
// Cubit — one line, macro generates everything else
// ---------------------------------------------------------------------------
/// Counter reactor — all boilerplate is generated by `#[reactor(state = CounterState)]`.
///
/// The macro generates:
/// - `impl Reactor for CounterReactor` (state(), emit() with change-detection)
/// - `pub fn new(initial: CounterState) -> Self`
/// - `subscribe()` and `attach_listener()` for observing transitions
#[reactor(state = CounterState)]
pub struct CounterReactor {}
impl CounterReactor {
    /// Increases the count by 1.
    pub fn increment(&mut self) {
        let next = self.state().count + 1;
        self.emit(CounterState::new(next));
    }
    /// Decreases the count by 1.
    pub fn decrement(&mut self) {
        let next = self.state().count - 1;
        self.emit(CounterState::new(next));
    }
    /// Resets the count to 0. No-op if already at 0 (change-detection).
    pub fn reset(&mut self) {
        self.emit(CounterState::new(0));
    }
}
// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------
