//! # GLoC Task Manager CLI
//!
//! A fully interactive terminal application that demonstrates GLoC's reactive
//! state management without any UI framework — pure `std::io`.
//!
//! ## Features demonstrated
//!
//! | Pattern | Where |
//! |---------|-------|
//! | `#[reactor(state = T)]` Mode A | `TaskReactor` |
//! | `neutrons = E` — neutron firing | `TaskReactor` + `TaskEvent` |
//! | `reactor.fire(neutron)` entry-point | REPL loop commands |
//! | Deref to state fields | `reactor.tasks`, `reactor.filter` |
//! | Change-detection (no-op guard) | Duplicate filter command |
//!
//! ## Usage
//!
//! ```sh
//! cargo run -p gloc-example-cli
//! ```
//!
//! Then type:
//!
//! ```text
//! add Buy groceries
//! add Write tests
//! list
//! done 1
//! filter active
//! list
//! quit
//! ```

use std::io::{self, BufRead, Write as IoWrite};

use gloc::{reactor, reactor_state, Reactor};

// ---------------------------------------------------------------------------
// Domain types
// ---------------------------------------------------------------------------

/// A single task in the list.
///
/// Each task has a unique auto-incremented `id`, a `title` entered by the user,
/// and a `done` flag toggled by the `done <id>` command.
#[derive(Clone, PartialEq, Debug)]
pub struct Task {
    /// Auto-incremented unique identifier for this task.
    pub id: u32,
    /// User-supplied description of the task.
    pub title: String,
    /// Whether the task has been marked as completed.
    pub done: bool,
}

/// Controls which tasks are visible in the `list` command output.
///
/// Mirrors the classic TodoMVC filter pattern so users can focus on
/// what is still pending or review what has already been completed.
#[derive(Clone, PartialEq, Debug, Default)]
pub enum Filter {
    /// Show every task regardless of completion status.
    #[default]
    All,
    /// Show only tasks where `done == false`.
    Active,
    /// Show only tasks where `done == true`.
    Done,
}

impl Filter {
    /// Returns the human-readable label used in transition output.
    fn label(&self) -> &'static str {
        match self {
            Filter::All => "All",
            Filter::Active => "Active",
            Filter::Done => "Done",
        }
    }
}

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------

/// Complete snapshot of the task manager at a single point in time.
///
/// Keeping `tasks` and `filter` together in one atomic state ensures that
/// observers always see a consistent picture — there is no intermediate
/// state where the list has been updated but the filter has not yet changed.
#[reactor_state]
pub struct TaskState {
    /// The ordered list of all tasks regardless of filter.
    pub tasks: Vec<Task>,
    /// The active display filter — defaults to `Filter::All`.
    pub filter: Filter,
    /// Auto-increment counter used to assign stable task IDs.
    pub next_id: u32,
}

impl TaskState {
    /// Constructs an empty `TaskState` ready to accept tasks.
    pub fn empty() -> Self {
        Self {
            tasks: Vec::new(),
            filter: Filter::All,
            next_id: 1,
        }
    }
}

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------

/// All the commands a user can send to `TaskReactor` through the event bus.
///
/// Using an event enum alongside direct methods demonstrates that both styles
/// coexist on the same reactor — pick the one that fits your context.
#[derive(Debug)]
pub enum TaskEvent {
    /// Add a new task with the given title string.
    Add(String),
    /// Mark the task with this ID as completed.
    Complete(u32),
    /// Permanently remove the task with this ID.
    Remove(u32),
    /// Change the active display filter.
    SetFilter(Filter),
}

// ---------------------------------------------------------------------------
// Reactor
// ---------------------------------------------------------------------------

/// Manages the full task list, including ordering, IDs, and the active filter.
///
/// `#[reactor(state = TaskState, neutrons = TaskEvent)]` generates:
/// - `impl Reactor for TaskReactor` — `state()`, `emit()` with change-detection
/// - `pub fn new(initial: TaskState) -> Self`
/// - `pub fn fire(&mut self, neutron: TaskEvent)` — calls `self.on_event(neutron)`
/// - `subscribe()`, `attach_listener()`
///
/// The `Deref` impl generated by the macro lets callers write
/// `reactor.tasks` / `reactor.filter` directly instead of
/// `reactor.state().tasks` / `reactor.state().filter`.
#[reactor(state = TaskState, neutrons = TaskEvent)]
pub struct TaskReactor {}

impl TaskReactor {
    // -- Direct methods (called from the REPL loop directly) -----------------

    /// Appends a new task with the given `title` and the next available ID.
    ///
    /// Prints a confirmation line **before** emitting so the message appears
    /// before any observer fires, giving a natural read order.
    pub fn add(&mut self, title: String) {
        let id = self.state().next_id;
        println!("[TaskReactor] Added: {:?} (id={})", title, id);

        let mut next = self.state().clone();
        next.tasks.push(Task {
            id,
            title,
            done: false,
        });
        next.next_id += 1;
        self.emit(next);
    }

    /// Marks the task with the given `id` as completed.
    ///
    /// Silently ignores unknown IDs — the user sees feedback via the
    /// "No task with id=N" message, consistent with CLI conventions.
    pub fn complete(&mut self, id: u32) {
        let mut next = self.state().clone();
        if let Some(task) = next.tasks.iter_mut().find(|t| t.id == id) {
            println!("[TaskReactor] Completed: {:?}", task.title);
            task.done = true;
        } else {
            println!("[TaskReactor] No task with id={}", id);
            return;
        }
        self.emit(next);
    }

    /// Removes the task with the given `id` from the list permanently.
    ///
    /// Returns early without emitting if no task matches, preserving
    /// GLoC's change-detection invariant (don't emit unchanged state).
    pub fn remove(&mut self, id: u32) {
        let mut next = self.state().clone();
        let before = next.tasks.len();
        next.tasks.retain(|t| t.id != id);
        if next.tasks.len() == before {
            println!("[TaskReactor] No task with id={}", id);
            return;
        }
        println!("[TaskReactor] Removed task id={}", id);
        self.emit(next);
    }

    /// Changes the active display filter.
    ///
    /// Demonstrates GLoC's change-detection: if the user types
    /// `filter all` twice, only the first emit notifies observers.
    pub fn set_filter(&mut self, filter: Filter) {
        println!("[TaskReactor] Filter: {}", filter.label());
        let mut next = self.state().clone();
        next.filter = filter;
        self.emit(next);
    }

    // -- on_event — required when `neutrons = TaskEvent` is used ---------------

    /// Routes each `TaskEvent` variant to the appropriate direct method.
    ///
    /// The macro generates `pub fn fire(neutron: TaskEvent)` which calls
    /// this function. The user owns this implementation — the macro only
    /// generates the public entry-point wrapper.
    fn on_event(&mut self, event: TaskEvent) {
        match event {
            TaskEvent::Add(title) => self.add(title),
            TaskEvent::Complete(id) => self.complete(id),
            TaskEvent::Remove(id) => self.remove(id),
            TaskEvent::SetFilter(filter) => self.set_filter(filter),
        }
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Prints the currently visible tasks according to the active filter.
///
/// Accesses `reactor.tasks` and `reactor.filter` via the generated `Deref`
/// impl so callers never need to write `reactor.state().tasks`.
fn print_list(reactor: &TaskReactor) {
    let visible: Vec<&Task> = reactor
        .tasks
        .iter()
        .filter(|t| match reactor.filter {
            Filter::All => true,
            Filter::Active => !t.done,
            Filter::Done => t.done,
        })
        .collect();

    if visible.is_empty() {
        println!("  (no tasks)");
    } else {
        for task in visible {
            let mark = if task.done { "x" } else { " " };
            println!("  [{}] {}. {}", mark, task.id, task.title);
        }
    }
}

/// Parses a `filter <all|active|done>` token into a `Filter` variant.
///
/// Returns `None` and prints a hint when the token is unrecognised, so
/// the REPL loop can skip dispatching without crashing.
fn parse_filter(token: &str) -> Option<Filter> {
    match token.to_lowercase().as_str() {
        "all" => Some(Filter::All),
        "active" => Some(Filter::Active),
        "done" => Some(Filter::Done),
        other => {
            println!("Unknown filter {:?}. Use: all | active | done", other);
            None
        }
    }
}

// ---------------------------------------------------------------------------
// Main REPL loop
// ---------------------------------------------------------------------------

fn main() {
    println!("GLoC Task Manager");
    println!(
        "Commands: add <title> | done <id> | rm <id> | filter <all|active|done> | list | quit"
    );

    let mut reactor = TaskReactor::new(TaskState::empty());

    let stdin = io::stdin();
    let stdout = io::stdout();

    loop {
        // Print prompt before reading each line.
        {
            let mut out = stdout.lock();
            out.write_all(b"\n> ").expect("failed to write prompt");
            out.flush().expect("failed to flush stdout");
        }

        let mut line = String::new();
        match stdin.lock().read_line(&mut line) {
            Ok(0) => {
                // EOF — user closed stdin (e.g. Ctrl-D)
                println!("\nGoodbye!");
                break;
            }
            Ok(_) => {}
            Err(e) => {
                eprintln!("Read error: {}", e);
                break;
            }
        }

        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }

        // Split into command keyword + everything after the first whitespace.
        let (cmd, rest) = trimmed
            .split_once(char::is_whitespace)
            .map(|(c, r)| (c, r.trim()))
            .unwrap_or((trimmed, ""));

        match cmd {
            "add" => {
                if rest.is_empty() {
                    println!("Usage: add <title>");
                } else {
                    reactor.fire(TaskEvent::Add(rest.to_string()));
                }
            }

            "done" => match rest.parse::<u32>() {
                Ok(id) => reactor.fire(TaskEvent::Complete(id)),
                Err(_) => println!("Usage: done <id>  (id must be a positive integer)"),
            },

            "rm" => match rest.parse::<u32>() {
                Ok(id) => reactor.fire(TaskEvent::Remove(id)),
                Err(_) => println!("Usage: rm <id>  (id must be a positive integer)"),
            },

            "filter" => {
                if let Some(filter) = parse_filter(rest) {
                    reactor.fire(TaskEvent::SetFilter(filter));
                }
            }

            "list" => print_list(&reactor),

            "quit" | "exit" | "q" => {
                println!("Goodbye!");
                break;
            }

            unknown => {
                println!(
                    "Unknown command {:?}. Try: add | done | rm | filter | list | quit",
                    unknown
                );
            }
        }
    }
}
